#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

# Autostart
if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal  --output DP-2 --mode 1920x1080 --rotate normal --left-of eDP-1
fi


nm-applet &
$HOME/.config/polybar/launch.sh
feh --bg-fill /usr/share/backgrounds/bspwm/Colors.jpg
picom &

#bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d I II III IV V

# Workspaces
bspc monitor DP-2 -d V VI VII VIII &
bspc monitor eDP-1 -d I II III IV &
# startup

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


