#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
if [[ $(xrandr -q | grep 'DP2 connected') ]]; then
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal  --output DP2 --mode 1920x1080 --rotate normal --left-of eDP1
fi
setxkbmap us &
nitrogen --restore &
light-locker &
/usr/bin/dunst &
picom &
redshift-gtk &
bash ~/.config/polybar/launch.sh &
# bash ~/.config/polybar/launch.sh --forest &


# Workspaces
bspc monitor DP2 -d V VI VII VIII &
bspc monitor eDP1 -d I II III IV &
# startup

bspc rule -a nemo desktop='^VI'
bspc rule -a firefox desktop='^V'
bspc rule -a code desktop='^IV'
bspc rule -a vlc state=floating desktop='^V'
bspc rule -a TelegramDesktop state=floating desktop='^V'

# Other stuff
bspc config border_width         2
bspc config window_gap           16
bspc config split_ratio          .50
bspc config top_padding          24
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#616161"
