window:
  dynamic_title: true
  dimensions:
    columns: 0
    lines: 0

  position:
    x: 50
    y: 50

  #startup_mode: SimpleFullscreen
  #position:
  #x: 0
  #y: 0

  padding:
    x: 10
    y: 10

  dynamic_padding: false
  decorations: none

scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: Source Code Pro
    style: Regular

  bold:
    family: Source Code Pro
    style: Bold

  italic:
    family: Source Code Pro
    style: Bold Italic

  size: 6.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x282828'
    foreground: '0xebdbb2'

  normal:
    black: '0x282828'
    red: '0xcc241d'
    green: '0x98971a'
    yellow: '0xd79921'
    blue: '0x458588'
    magenta: '0xb16286'
    cyan: '0x689d6a'
    white: '0xa89984'

  bright:
    black: '0x928374'
    red: '0xfb4934'
    green: '0xb8bb26'
    yellow: '0xfabd2f'
    blue: '0x83a598'
    magenta: '0xd3869b'
    cyan: '0x8ec07c'
    white: '0xebdbb2'
# background_opacity: 0.95
